//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 03:09:19 PM CST 
//


package com.asi.huanan.service.dao.mybatis.model.customerize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QueryResult">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QueryNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Degree21" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="Drkcnt21" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="Drkfee21" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="Ttprem" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="Query21" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Errmsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Errmsg_af" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Degree01" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="Degree31" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="Degree24" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="Degree15" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="QueryNo_af" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="exddat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="typveh" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cindate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="QueryDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryResult"
})
@XmlRootElement(name = "QueryResponse")
public class QueryResponse {

    @XmlElement(name = "QueryResult", required = true)
    protected QueryResponse.QueryResult queryResult;

    /**
     * Gets the value of the queryResult property.
     * 
     * @return
     *     possible object is
     *     {@link QueryResponse.QueryResult }
     *     
     */
    public QueryResponse.QueryResult getQueryResult() {
        return queryResult;
    }

    /**
     * Sets the value of the queryResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryResponse.QueryResult }
     *     
     */
    public void setQueryResult(QueryResponse.QueryResult value) {
        this.queryResult = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="QueryNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Degree21" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *         &lt;element name="Drkcnt21" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *         &lt;element name="Drkfee21" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *         &lt;element name="Ttprem" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="Query21" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Errmsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Errmsg_af" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Degree01" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *         &lt;element name="Degree31" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *         &lt;element name="Degree24" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *         &lt;element name="Degree15" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *         &lt;element name="QueryNo_af" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="exddat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="typveh" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cindate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="QueryDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
    	"Sendstring",
    	"Sendstring21",
    	"RetString",
    	"RetString21",
        "queryNo",
        "degree21",
        "drkcnt21",
        "drkfee21",
        "ttprem",
        "query21",
        "errmsg",
        "errmsgAf",
        "degree01",
        "degree31",
        "degree24",
        "degree15",
        "queryNoAf",
        "exddat",
        "typveh",
        "engino",
        "carnox",
        "ins1",
    	"ins2",
    	"ins3",
    	"ins4",
    	"ins5",
    	"ins6",
    	"ins7",
    	"ins8",
    	"ins9",
    	"ins10",
    	"ins11",
    	"ins12",
    	"ins13",
    	"query_type",
    	"Buffer1",
    	"Buffer21",
    	"CkValue",
    	"Ova",
        "cindate",
        "queryDateTime"
    })
    public static class QueryResult {

    	@XmlElement(name = "Sendstring", required = true)
    	protected String Sendstring;
    	@XmlElement(name = "Sendstring21", required = true)
    	protected String Sendstring21;
    	@XmlElement(name = "RetString", required = true)
    	protected String RetString;
    	@XmlElement(name = "RetString21", required = true)
    	protected String RetString21;
        @XmlElement(name = "QueryNo", required = true)
        protected String queryNo;
        @XmlElement(name = "Degree21", required = true)
        protected String degree21;
        @XmlElement(name = "Drkcnt21", required = true)
        protected String drkcnt21;
        @XmlElement(name = "Drkfee21", required = true)
        protected String drkfee21;
        @XmlElement(name = "Ttprem", required = true)
        protected short ttprem;
        @XmlElement(name = "Query21", required = true)
        protected String query21;
        @XmlElement(name = "Errmsg", required = true)
        protected String errmsg;
        @XmlElement(name = "Errmsg_af", required = true)
        protected String errmsgAf;
        @XmlElement(name = "Degree01", required = true)
        protected String degree01;
        @XmlElement(name = "Degree31", required = true)
        protected String degree31;
        @XmlElement(name = "Degree24", required = true)
        protected String degree24;
        @XmlElement(name = "Degree15", required = true)
        protected String degree15;
        @XmlElement(name = "QueryNo_af", required = true)
        protected String queryNoAf;
        @XmlElement(name = "exddat", required = true)
        protected String exddat;
        @XmlElement(name = "typveh", required = true)
        protected String typveh;
        @XmlElement(name = "engino", required = true)
        protected String engino;
        @XmlElement(name = "carnox", required = true)
        protected String carnox;
        @XmlElement(name = "ins1", required = true)
        protected String ins1;
        @XmlElement(name = "ins2", required = true)
        protected String ins2;
        @XmlElement(name = "ins3", required = true)
        protected String ins3;
        @XmlElement(name = "ins4", required = true)
        protected String ins4;
        @XmlElement(name = "ins5", required = true)
        protected String ins5;
        @XmlElement(name = "ins6", required = true)
        protected String ins6;
        @XmlElement(name = "ins7", required = true)
        protected String ins7;
        @XmlElement(name = "ins8", required = true)
        protected String ins8;
        @XmlElement(name = "ins9", required = true)
        protected String ins9;
        @XmlElement(name = "ins10", required = true)
        protected String ins10;
        @XmlElement(name = "ins11", required = true)
        protected String ins11;
        @XmlElement(name = "ins12", required = true)
        protected String ins12;
        @XmlElement(name = "ins13", required = true)
        protected String ins13;
        @XmlElement(name = "query_type", required = true)
        protected String query_type;
        @XmlElement(name = "Buffer1", required = true)
        protected String Buffer1;
        @XmlElement(name = "Buffer21", required = true)
        protected String Buffer21;
        @XmlElement(name = "CkValue", required = true)
        protected String CkValue;
        @XmlElement(name = "Ova", required = true)
        protected String Ova;
        @XmlElement(required = true)
        protected String cindate;
        @XmlElement(name = "QueryDateTime", required = true)
        protected String queryDateTime;
		public String getSendstring() {
			return Sendstring;
		}
		public void setSendstring(String sendstring) {
			Sendstring = sendstring;
		}
		public String getSendstring21() {
			return Sendstring21;
		}
		public void setSendstring21(String sendstring21) {
			Sendstring21 = sendstring21;
		}
		public String getRetString() {
			return RetString;
		}
		public void setRetString(String retString) {
			RetString = retString;
		}
		public String getRetString21() {
			return RetString21;
		}
		public void setRetString21(String retString21) {
			RetString21 = retString21;
		}
		public String getQueryNo() {
			return queryNo;
		}
		public void setQueryNo(String queryNo) {
			this.queryNo = queryNo;
		}
		public String getDegree21() {
			return degree21;
		}
		public void setDegree21(String degree21) {
			this.degree21 = degree21;
		}
		public String getDrkcnt21() {
			return drkcnt21;
		}
		public void setDrkcnt21(String drkcnt21) {
			this.drkcnt21 = drkcnt21;
		}
		public String getDrkfee21() {
			return drkfee21;
		}
		public void setDrkfee21(String drkfee21) {
			this.drkfee21 = drkfee21;
		}
		public short getTtprem() {
			return ttprem;
		}
		public void setTtprem(short ttprem) {
			this.ttprem = ttprem;
		}
		public String getQuery21() {
			return query21;
		}
		public void setQuery21(String query21) {
			this.query21 = query21;
		}
		public String getErrmsg() {
			return errmsg;
		}
		public void setErrmsg(String errmsg) {
			this.errmsg = errmsg;
		}
		public String getErrmsgAf() {
			return errmsgAf;
		}
		public void setErrmsgAf(String errmsgAf) {
			this.errmsgAf = errmsgAf;
		}
		public String getDegree01() {
			return degree01;
		}
		public void setDegree01(String degree01) {
			this.degree01 = degree01;
		}
		public String getDegree31() {
			return degree31;
		}
		public void setDegree31(String degree31) {
			this.degree31 = degree31;
		}
		public String getDegree24() {
			return degree24;
		}
		public void setDegree24(String degree24) {
			this.degree24 = degree24;
		}
		public String getDegree15() {
			return degree15;
		}
		public void setDegree15(String degree15) {
			this.degree15 = degree15;
		}
		public String getQueryNoAf() {
			return queryNoAf;
		}
		public void setQueryNoAf(String queryNoAf) {
			this.queryNoAf = queryNoAf;
		}
		public String getExddat() {
			return exddat;
		}
		public void setExddat(String exddat) {
			this.exddat = exddat;
		}
		public String getTypveh() {
			return typveh;
		}
		public void setTypveh(String typveh) {
			this.typveh = typveh;
		}
		public String getEngino() {
			return engino;
		}
		public void setEngino(String engino) {
			this.engino = engino;
		}
		public String getCarnox() {
			return carnox;
		}
		public void setCarnox(String carnox) {
			this.carnox = carnox;
		}
		public String getIns1() {
			return ins1;
		}
		public void setIns1(String ins1) {
			this.ins1 = ins1;
		}
		public String getIns2() {
			return ins2;
		}
		public void setIns2(String ins2) {
			this.ins2 = ins2;
		}
		public String getIns3() {
			return ins3;
		}
		public void setIns3(String ins3) {
			this.ins3 = ins3;
		}
		public String getIns4() {
			return ins4;
		}
		public void setIns4(String ins4) {
			this.ins4 = ins4;
		}
		public String getIns5() {
			return ins5;
		}
		public void setIns5(String ins5) {
			this.ins5 = ins5;
		}
		public String getIns6() {
			return ins6;
		}
		public void setIns6(String ins6) {
			this.ins6 = ins6;
		}
		public String getIns7() {
			return ins7;
		}
		public void setIns7(String ins7) {
			this.ins7 = ins7;
		}
		public String getIns8() {
			return ins8;
		}
		public void setIns8(String ins8) {
			this.ins8 = ins8;
		}
		public String getIns9() {
			return ins9;
		}
		public void setIns9(String ins9) {
			this.ins9 = ins9;
		}
		public String getIns10() {
			return ins10;
		}
		public void setIns10(String ins10) {
			this.ins10 = ins10;
		}
		public String getIns11() {
			return ins11;
		}
		public void setIns11(String ins11) {
			this.ins11 = ins11;
		}
		public String getIns12() {
			return ins12;
		}
		public void setIns12(String ins12) {
			this.ins12 = ins12;
		}
		public String getIns13() {
			return ins13;
		}
		public void setIns13(String ins13) {
			this.ins13 = ins13;
		}
		public String getQuery_type() {
			return query_type;
		}
		public void setQuery_type(String query_type) {
			this.query_type = query_type;
		}
		public String getBuffer1() {
			return Buffer1;
		}
		public void setBuffer1(String buffer1) {
			Buffer1 = buffer1;
		}
		public String getBuffer21() {
			return Buffer21;
		}
		public void setBuffer21(String buffer21) {
			Buffer21 = buffer21;
		}
		public String getCkValue() {
			return CkValue;
		}
		public void setCkValue(String ckValue) {
			CkValue = ckValue;
		}
		public String getOva() {
			return Ova;
		}
		public void setOva(String ova) {
			Ova = ova;
		}
		public String getCindate() {
			return cindate;
		}
		public void setCindate(String cindate) {
			this.cindate = cindate;
		}
		public String getQueryDateTime() {
			return queryDateTime;
		}
		public void setQueryDateTime(String queryDateTime) {
			this.queryDateTime = queryDateTime;
		}

    }

}
