package com.asi.service.dao.mybatis.model;

import java.util.Date;

public class AppHoliday {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column APP_HOLIDAY.UUID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column APP_HOLIDAY.HOLIDAY
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	private Date holiday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column APP_HOLIDAY.MEMO
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column APP_HOLIDAY.STATUS
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column APP_HOLIDAY.CRT_DATE
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	private String crtDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column APP_HOLIDAY.CRT_USERID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	private Date crtUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column APP_HOLIDAY.ENTRY_USERID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	private String entryUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column APP_HOLIDAY.ENTRY_DATE
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	private Date entryDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column APP_HOLIDAY.UUID
	 * @return  the value of APP_HOLIDAY.UUID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column APP_HOLIDAY.UUID
	 * @param uuid  the value for APP_HOLIDAY.UUID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column APP_HOLIDAY.HOLIDAY
	 * @return  the value of APP_HOLIDAY.HOLIDAY
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public Date getHoliday() {
		return holiday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column APP_HOLIDAY.HOLIDAY
	 * @param holiday  the value for APP_HOLIDAY.HOLIDAY
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public void setHoliday(Date holiday) {
		this.holiday = holiday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column APP_HOLIDAY.MEMO
	 * @return  the value of APP_HOLIDAY.MEMO
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column APP_HOLIDAY.MEMO
	 * @param memo  the value for APP_HOLIDAY.MEMO
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column APP_HOLIDAY.STATUS
	 * @return  the value of APP_HOLIDAY.STATUS
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column APP_HOLIDAY.STATUS
	 * @param status  the value for APP_HOLIDAY.STATUS
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column APP_HOLIDAY.CRT_DATE
	 * @return  the value of APP_HOLIDAY.CRT_DATE
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public String getCrtDate() {
		return crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column APP_HOLIDAY.CRT_DATE
	 * @param crtDate  the value for APP_HOLIDAY.CRT_DATE
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public void setCrtDate(String crtDate) {
		this.crtDate = crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column APP_HOLIDAY.CRT_USERID
	 * @return  the value of APP_HOLIDAY.CRT_USERID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public Date getCrtUserid() {
		return crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column APP_HOLIDAY.CRT_USERID
	 * @param crtUserid  the value for APP_HOLIDAY.CRT_USERID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public void setCrtUserid(Date crtUserid) {
		this.crtUserid = crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column APP_HOLIDAY.ENTRY_USERID
	 * @return  the value of APP_HOLIDAY.ENTRY_USERID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public String getEntryUserid() {
		return entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column APP_HOLIDAY.ENTRY_USERID
	 * @param entryUserid  the value for APP_HOLIDAY.ENTRY_USERID
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public void setEntryUserid(String entryUserid) {
		this.entryUserid = entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column APP_HOLIDAY.ENTRY_DATE
	 * @return  the value of APP_HOLIDAY.ENTRY_DATE
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column APP_HOLIDAY.ENTRY_DATE
	 * @param entryDate  the value for APP_HOLIDAY.ENTRY_DATE
	 * @mbg.generated  Wed Apr 10 17:56:57 CST 2019
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}
}