package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysAccountExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public SysAccountExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserRoleIsNull() {
			addCriterion("user_role is null");
			return (Criteria) this;
		}

		public Criteria andUserRoleIsNotNull() {
			addCriterion("user_role is not null");
			return (Criteria) this;
		}

		public Criteria andUserRoleEqualTo(String value) {
			addCriterion("user_role =", value, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleNotEqualTo(String value) {
			addCriterion("user_role <>", value, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleGreaterThan(String value) {
			addCriterion("user_role >", value, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleGreaterThanOrEqualTo(String value) {
			addCriterion("user_role >=", value, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleLessThan(String value) {
			addCriterion("user_role <", value, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleLessThanOrEqualTo(String value) {
			addCriterion("user_role <=", value, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleLike(String value) {
			addCriterion("user_role like", value, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleNotLike(String value) {
			addCriterion("user_role not like", value, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleIn(List<String> values) {
			addCriterion("user_role in", values, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleNotIn(List<String> values) {
			addCriterion("user_role not in", values, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleBetween(String value1, String value2) {
			addCriterion("user_role between", value1, value2, "userRole");
			return (Criteria) this;
		}

		public Criteria andUserRoleNotBetween(String value1, String value2) {
			addCriterion("user_role not between", value1, value2, "userRole");
			return (Criteria) this;
		}

		public Criteria andDeptidIsNull() {
			addCriterion("deptid is null");
			return (Criteria) this;
		}

		public Criteria andDeptidIsNotNull() {
			addCriterion("deptid is not null");
			return (Criteria) this;
		}

		public Criteria andDeptidEqualTo(String value) {
			addCriterion("deptid =", value, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidNotEqualTo(String value) {
			addCriterion("deptid <>", value, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidGreaterThan(String value) {
			addCriterion("deptid >", value, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidGreaterThanOrEqualTo(String value) {
			addCriterion("deptid >=", value, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidLessThan(String value) {
			addCriterion("deptid <", value, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidLessThanOrEqualTo(String value) {
			addCriterion("deptid <=", value, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidLike(String value) {
			addCriterion("deptid like", value, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidNotLike(String value) {
			addCriterion("deptid not like", value, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidIn(List<String> values) {
			addCriterion("deptid in", values, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidNotIn(List<String> values) {
			addCriterion("deptid not in", values, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidBetween(String value1, String value2) {
			addCriterion("deptid between", value1, value2, "deptid");
			return (Criteria) this;
		}

		public Criteria andDeptidNotBetween(String value1, String value2) {
			addCriterion("deptid not between", value1, value2, "deptid");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(BigDecimal value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(BigDecimal value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(BigDecimal value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(BigDecimal value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(BigDecimal value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<BigDecimal> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<BigDecimal> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andMailIsNull() {
			addCriterion("mail is null");
			return (Criteria) this;
		}

		public Criteria andMailIsNotNull() {
			addCriterion("mail is not null");
			return (Criteria) this;
		}

		public Criteria andMailEqualTo(String value) {
			addCriterion("mail =", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailNotEqualTo(String value) {
			addCriterion("mail <>", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailGreaterThan(String value) {
			addCriterion("mail >", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailGreaterThanOrEqualTo(String value) {
			addCriterion("mail >=", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailLessThan(String value) {
			addCriterion("mail <", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailLessThanOrEqualTo(String value) {
			addCriterion("mail <=", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailLike(String value) {
			addCriterion("mail like", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailNotLike(String value) {
			addCriterion("mail not like", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailIn(List<String> values) {
			addCriterion("mail in", values, "mail");
			return (Criteria) this;
		}

		public Criteria andMailNotIn(List<String> values) {
			addCriterion("mail not in", values, "mail");
			return (Criteria) this;
		}

		public Criteria andMailBetween(String value1, String value2) {
			addCriterion("mail between", value1, value2, "mail");
			return (Criteria) this;
		}

		public Criteria andMailNotBetween(String value1, String value2) {
			addCriterion("mail not between", value1, value2, "mail");
			return (Criteria) this;
		}

		public Criteria andErrorIsNull() {
			addCriterion("error is null");
			return (Criteria) this;
		}

		public Criteria andErrorIsNotNull() {
			addCriterion("error is not null");
			return (Criteria) this;
		}

		public Criteria andErrorEqualTo(BigDecimal value) {
			addCriterion("error =", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotEqualTo(BigDecimal value) {
			addCriterion("error <>", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorGreaterThan(BigDecimal value) {
			addCriterion("error >", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("error >=", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorLessThan(BigDecimal value) {
			addCriterion("error <", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorLessThanOrEqualTo(BigDecimal value) {
			addCriterion("error <=", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorIn(List<BigDecimal> values) {
			addCriterion("error in", values, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotIn(List<BigDecimal> values) {
			addCriterion("error not in", values, "error");
			return (Criteria) this;
		}

		public Criteria andErrorBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("error between", value1, value2, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("error not between", value1, value2, "error");
			return (Criteria) this;
		}

		public Criteria andAreaidIsNull() {
			addCriterion("areaid is null");
			return (Criteria) this;
		}

		public Criteria andAreaidIsNotNull() {
			addCriterion("areaid is not null");
			return (Criteria) this;
		}

		public Criteria andAreaidEqualTo(String value) {
			addCriterion("areaid =", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidNotEqualTo(String value) {
			addCriterion("areaid <>", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidGreaterThan(String value) {
			addCriterion("areaid >", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidGreaterThanOrEqualTo(String value) {
			addCriterion("areaid >=", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidLessThan(String value) {
			addCriterion("areaid <", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidLessThanOrEqualTo(String value) {
			addCriterion("areaid <=", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidLike(String value) {
			addCriterion("areaid like", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidNotLike(String value) {
			addCriterion("areaid not like", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidIn(List<String> values) {
			addCriterion("areaid in", values, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidNotIn(List<String> values) {
			addCriterion("areaid not in", values, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidBetween(String value1, String value2) {
			addCriterion("areaid between", value1, value2, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidNotBetween(String value1, String value2) {
			addCriterion("areaid not between", value1, value2, "areaid");
			return (Criteria) this;
		}

		public Criteria andEnableMarkIsNull() {
			addCriterion("enable_mark is null");
			return (Criteria) this;
		}

		public Criteria andEnableMarkIsNotNull() {
			addCriterion("enable_mark is not null");
			return (Criteria) this;
		}

		public Criteria andEnableMarkEqualTo(String value) {
			addCriterion("enable_mark =", value, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkNotEqualTo(String value) {
			addCriterion("enable_mark <>", value, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkGreaterThan(String value) {
			addCriterion("enable_mark >", value, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkGreaterThanOrEqualTo(String value) {
			addCriterion("enable_mark >=", value, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkLessThan(String value) {
			addCriterion("enable_mark <", value, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkLessThanOrEqualTo(String value) {
			addCriterion("enable_mark <=", value, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkLike(String value) {
			addCriterion("enable_mark like", value, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkNotLike(String value) {
			addCriterion("enable_mark not like", value, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkIn(List<String> values) {
			addCriterion("enable_mark in", values, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkNotIn(List<String> values) {
			addCriterion("enable_mark not in", values, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkBetween(String value1, String value2) {
			addCriterion("enable_mark between", value1, value2, "enableMark");
			return (Criteria) this;
		}

		public Criteria andEnableMarkNotBetween(String value1, String value2) {
			addCriterion("enable_mark not between", value1, value2, "enableMark");
			return (Criteria) this;
		}

		public Criteria andCrtUseridIsNull() {
			addCriterion("crt_userid is null");
			return (Criteria) this;
		}

		public Criteria andCrtUseridIsNotNull() {
			addCriterion("crt_userid is not null");
			return (Criteria) this;
		}

		public Criteria andCrtUseridEqualTo(String value) {
			addCriterion("crt_userid =", value, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridNotEqualTo(String value) {
			addCriterion("crt_userid <>", value, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridGreaterThan(String value) {
			addCriterion("crt_userid >", value, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridGreaterThanOrEqualTo(String value) {
			addCriterion("crt_userid >=", value, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridLessThan(String value) {
			addCriterion("crt_userid <", value, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridLessThanOrEqualTo(String value) {
			addCriterion("crt_userid <=", value, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridLike(String value) {
			addCriterion("crt_userid like", value, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridNotLike(String value) {
			addCriterion("crt_userid not like", value, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridIn(List<String> values) {
			addCriterion("crt_userid in", values, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridNotIn(List<String> values) {
			addCriterion("crt_userid not in", values, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridBetween(String value1, String value2) {
			addCriterion("crt_userid between", value1, value2, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtUseridNotBetween(String value1, String value2) {
			addCriterion("crt_userid not between", value1, value2, "crtUserid");
			return (Criteria) this;
		}

		public Criteria andCrtDateIsNull() {
			addCriterion("crt_date is null");
			return (Criteria) this;
		}

		public Criteria andCrtDateIsNotNull() {
			addCriterion("crt_date is not null");
			return (Criteria) this;
		}

		public Criteria andCrtDateEqualTo(Date value) {
			addCriterion("crt_date =", value, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateNotEqualTo(Date value) {
			addCriterion("crt_date <>", value, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateGreaterThan(Date value) {
			addCriterion("crt_date >", value, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateGreaterThanOrEqualTo(Date value) {
			addCriterion("crt_date >=", value, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateLessThan(Date value) {
			addCriterion("crt_date <", value, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateLessThanOrEqualTo(Date value) {
			addCriterion("crt_date <=", value, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateIn(List<Date> values) {
			addCriterion("crt_date in", values, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateNotIn(List<Date> values) {
			addCriterion("crt_date not in", values, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateBetween(Date value1, Date value2) {
			addCriterion("crt_date between", value1, value2, "crtDate");
			return (Criteria) this;
		}

		public Criteria andCrtDateNotBetween(Date value1, Date value2) {
			addCriterion("crt_date not between", value1, value2, "crtDate");
			return (Criteria) this;
		}

		public Criteria andEntryUseridIsNull() {
			addCriterion("entry_userid is null");
			return (Criteria) this;
		}

		public Criteria andEntryUseridIsNotNull() {
			addCriterion("entry_userid is not null");
			return (Criteria) this;
		}

		public Criteria andEntryUseridEqualTo(String value) {
			addCriterion("entry_userid =", value, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridNotEqualTo(String value) {
			addCriterion("entry_userid <>", value, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridGreaterThan(String value) {
			addCriterion("entry_userid >", value, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridGreaterThanOrEqualTo(String value) {
			addCriterion("entry_userid >=", value, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridLessThan(String value) {
			addCriterion("entry_userid <", value, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridLessThanOrEqualTo(String value) {
			addCriterion("entry_userid <=", value, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridLike(String value) {
			addCriterion("entry_userid like", value, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridNotLike(String value) {
			addCriterion("entry_userid not like", value, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridIn(List<String> values) {
			addCriterion("entry_userid in", values, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridNotIn(List<String> values) {
			addCriterion("entry_userid not in", values, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridBetween(String value1, String value2) {
			addCriterion("entry_userid between", value1, value2, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryUseridNotBetween(String value1, String value2) {
			addCriterion("entry_userid not between", value1, value2, "entryUserid");
			return (Criteria) this;
		}

		public Criteria andEntryDateIsNull() {
			addCriterion("entry_date is null");
			return (Criteria) this;
		}

		public Criteria andEntryDateIsNotNull() {
			addCriterion("entry_date is not null");
			return (Criteria) this;
		}

		public Criteria andEntryDateEqualTo(Date value) {
			addCriterion("entry_date =", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateNotEqualTo(Date value) {
			addCriterion("entry_date <>", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateGreaterThan(Date value) {
			addCriterion("entry_date >", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateGreaterThanOrEqualTo(Date value) {
			addCriterion("entry_date >=", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateLessThan(Date value) {
			addCriterion("entry_date <", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateLessThanOrEqualTo(Date value) {
			addCriterion("entry_date <=", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateIn(List<Date> values) {
			addCriterion("entry_date in", values, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateNotIn(List<Date> values) {
			addCriterion("entry_date not in", values, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateBetween(Date value1, Date value2) {
			addCriterion("entry_date between", value1, value2, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateNotBetween(Date value1, Date value2) {
			addCriterion("entry_date not between", value1, value2, "entryDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table sys_account
	 *
	 * @mbg.generated do_not_delete_during_merge Tue Mar 31 14:00:52 CST 2020
	 */
	public static class Criteria extends GeneratedCriteria {
		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}