package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysAccount {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.user_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.user_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String userName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.user_role
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String userRole;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.deptid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String deptid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.password
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String password;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.status
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private BigDecimal status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.mail
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String mail;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.error
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private BigDecimal error;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.areaid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String areaid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String enableMark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String crtUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private Date crtDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String entryUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_account.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private Date entryDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.user_id
	 *
	 * @return the value of sys_account.user_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.user_id
	 *
	 * @param userId the value for sys_account.user_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.user_name
	 *
	 * @return the value of sys_account.user_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.user_name
	 *
	 * @param userName the value for sys_account.user_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.user_role
	 *
	 * @return the value of sys_account.user_role
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getUserRole() {
		return userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.user_role
	 *
	 * @param userRole the value for sys_account.user_role
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.deptid
	 *
	 * @return the value of sys_account.deptid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getDeptid() {
		return deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.deptid
	 *
	 * @param deptid the value for sys_account.deptid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.password
	 *
	 * @return the value of sys_account.password
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.password
	 *
	 * @param password the value for sys_account.password
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.status
	 *
	 * @return the value of sys_account.status
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public BigDecimal getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.status
	 *
	 * @param status the value for sys_account.status
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.mail
	 *
	 * @return the value of sys_account.mail
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.mail
	 *
	 * @param mail the value for sys_account.mail
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.error
	 *
	 * @return the value of sys_account.error
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public BigDecimal getError() {
		return error;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.error
	 *
	 * @param error the value for sys_account.error
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setError(BigDecimal error) {
		this.error = error;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.areaid
	 *
	 * @return the value of sys_account.areaid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getAreaid() {
		return areaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.areaid
	 *
	 * @param areaid the value for sys_account.areaid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.enable_mark
	 *
	 * @return the value of sys_account.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getEnableMark() {
		return enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.enable_mark
	 *
	 * @param enableMark the value for sys_account.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEnableMark(String enableMark) {
		this.enableMark = enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.crt_userid
	 *
	 * @return the value of sys_account.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getCrtUserid() {
		return crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.crt_userid
	 *
	 * @param crtUserid the value for sys_account.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setCrtUserid(String crtUserid) {
		this.crtUserid = crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.crt_date
	 *
	 * @return the value of sys_account.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public Date getCrtDate() {
		return crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.crt_date
	 *
	 * @param crtDate the value for sys_account.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.entry_userid
	 *
	 * @return the value of sys_account.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getEntryUserid() {
		return entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.entry_userid
	 *
	 * @param entryUserid the value for sys_account.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEntryUserid(String entryUserid) {
		this.entryUserid = entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_account.entry_date
	 *
	 * @return the value of sys_account.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_account.entry_date
	 *
	 * @param entryDate the value for sys_account.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}
}