package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysFunctionUiButton {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_function_ui_button.function_ui_button_id
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	private BigDecimal functionUiButtonId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_function_ui_button.function_ui_button_name
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	private String functionUiButtonName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_function_ui_button.enable_mark
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	private String enableMark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_function_ui_button.crt_userid
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	private String crtUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_function_ui_button.crt_date
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	private Date crtDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_function_ui_button.entry_userid
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	private String entryUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_function_ui_button.entry_date
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	private Date entryDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_function_ui_button.function_ui_button_id
	 *
	 * @return the value of sys_function_ui_button.function_ui_button_id
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public BigDecimal getFunctionUiButtonId() {
		return functionUiButtonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_function_ui_button.function_ui_button_id
	 *
	 * @param functionUiButtonId the value for
	 *                           sys_function_ui_button.function_ui_button_id
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public void setFunctionUiButtonId(BigDecimal functionUiButtonId) {
		this.functionUiButtonId = functionUiButtonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_function_ui_button.function_ui_button_name
	 *
	 * @return the value of sys_function_ui_button.function_ui_button_name
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public String getFunctionUiButtonName() {
		return functionUiButtonName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_function_ui_button.function_ui_button_name
	 *
	 * @param functionUiButtonName the value for
	 *                             sys_function_ui_button.function_ui_button_name
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public void setFunctionUiButtonName(String functionUiButtonName) {
		this.functionUiButtonName = functionUiButtonName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_function_ui_button.enable_mark
	 *
	 * @return the value of sys_function_ui_button.enable_mark
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public String getEnableMark() {
		return enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_function_ui_button.enable_mark
	 *
	 * @param enableMark the value for sys_function_ui_button.enable_mark
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public void setEnableMark(String enableMark) {
		this.enableMark = enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_function_ui_button.crt_userid
	 *
	 * @return the value of sys_function_ui_button.crt_userid
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public String getCrtUserid() {
		return crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_function_ui_button.crt_userid
	 *
	 * @param crtUserid the value for sys_function_ui_button.crt_userid
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public void setCrtUserid(String crtUserid) {
		this.crtUserid = crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_function_ui_button.crt_date
	 *
	 * @return the value of sys_function_ui_button.crt_date
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public Date getCrtDate() {
		return crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_function_ui_button.crt_date
	 *
	 * @param crtDate the value for sys_function_ui_button.crt_date
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_function_ui_button.entry_userid
	 *
	 * @return the value of sys_function_ui_button.entry_userid
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public String getEntryUserid() {
		return entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_function_ui_button.entry_userid
	 *
	 * @param entryUserid the value for sys_function_ui_button.entry_userid
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public void setEntryUserid(String entryUserid) {
		this.entryUserid = entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_function_ui_button.entry_date
	 *
	 * @return the value of sys_function_ui_button.entry_date
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_function_ui_button.entry_date
	 *
	 * @param entryDate the value for sys_function_ui_button.entry_date
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}
}