package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysIndex {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.index_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private BigDecimal indexId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.index_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String indexName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.index_func_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String indexFuncUrl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.index_icon_path
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String indexIconPath;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.index_sort
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private BigDecimal indexSort;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String enableMark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String crtUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private Date crtDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String entryUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private Date entryDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.index_id
	 *
	 * @return the value of sys_index.index_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public BigDecimal getIndexId() {
		return indexId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.index_id
	 *
	 * @param indexId the value for sys_index.index_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setIndexId(BigDecimal indexId) {
		this.indexId = indexId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.index_name
	 *
	 * @return the value of sys_index.index_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getIndexName() {
		return indexName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.index_name
	 *
	 * @param indexName the value for sys_index.index_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setIndexName(String indexName) {
		this.indexName = indexName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.index_func_url
	 *
	 * @return the value of sys_index.index_func_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getIndexFuncUrl() {
		return indexFuncUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.index_func_url
	 *
	 * @param indexFuncUrl the value for sys_index.index_func_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setIndexFuncUrl(String indexFuncUrl) {
		this.indexFuncUrl = indexFuncUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.index_icon_path
	 *
	 * @return the value of sys_index.index_icon_path
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getIndexIconPath() {
		return indexIconPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.index_icon_path
	 *
	 * @param indexIconPath the value for sys_index.index_icon_path
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setIndexIconPath(String indexIconPath) {
		this.indexIconPath = indexIconPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.index_sort
	 *
	 * @return the value of sys_index.index_sort
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public BigDecimal getIndexSort() {
		return indexSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.index_sort
	 *
	 * @param indexSort the value for sys_index.index_sort
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setIndexSort(BigDecimal indexSort) {
		this.indexSort = indexSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.enable_mark
	 *
	 * @return the value of sys_index.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getEnableMark() {
		return enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.enable_mark
	 *
	 * @param enableMark the value for sys_index.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEnableMark(String enableMark) {
		this.enableMark = enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.crt_userid
	 *
	 * @return the value of sys_index.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getCrtUserid() {
		return crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.crt_userid
	 *
	 * @param crtUserid the value for sys_index.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setCrtUserid(String crtUserid) {
		this.crtUserid = crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.crt_date
	 *
	 * @return the value of sys_index.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public Date getCrtDate() {
		return crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.crt_date
	 *
	 * @param crtDate the value for sys_index.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.entry_userid
	 *
	 * @return the value of sys_index.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getEntryUserid() {
		return entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.entry_userid
	 *
	 * @param entryUserid the value for sys_index.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEntryUserid(String entryUserid) {
		this.entryUserid = entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index.entry_date
	 *
	 * @return the value of sys_index.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index.entry_date
	 *
	 * @param entryDate the value for sys_index.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}
}