package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;

public class SysIndexRoleKey {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index_role.user_role
	 *
	 * @mbg.generated Thu Apr 16 17:57:02 CST 2020
	 */
	private String userRole;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_index_role.index_id
	 *
	 * @mbg.generated Thu Apr 16 17:57:02 CST 2020
	 */
	private BigDecimal indexId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index_role.user_role
	 *
	 * @return the value of sys_index_role.user_role
	 *
	 * @mbg.generated Thu Apr 16 17:57:02 CST 2020
	 */
	public String getUserRole() {
		return userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index_role.user_role
	 *
	 * @param userRole the value for sys_index_role.user_role
	 *
	 * @mbg.generated Thu Apr 16 17:57:02 CST 2020
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_index_role.index_id
	 *
	 * @return the value of sys_index_role.index_id
	 *
	 * @mbg.generated Thu Apr 16 17:57:02 CST 2020
	 */
	public BigDecimal getIndexId() {
		return indexId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_index_role.index_id
	 *
	 * @param indexId the value for sys_index_role.index_id
	 *
	 * @mbg.generated Thu Apr 16 17:57:02 CST 2020
	 */
	public void setIndexId(BigDecimal indexId) {
		this.indexId = indexId;
	}
}