package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysMenu {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.menu_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private BigDecimal menuId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.menu_upper_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private BigDecimal menuUpperId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.menu_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String menuName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.menu_func_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String menuFuncUrl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.menu_icon_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String menuIconUrl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.index_sort
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private BigDecimal indexSort;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String enableMark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String crtUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private Date crtDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private String entryUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	private Date entryDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.menu_id
	 *
	 * @return the value of sys_menu.menu_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public BigDecimal getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.menu_id
	 *
	 * @param menuId the value for sys_menu.menu_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setMenuId(BigDecimal menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.menu_upper_id
	 *
	 * @return the value of sys_menu.menu_upper_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public BigDecimal getMenuUpperId() {
		return menuUpperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.menu_upper_id
	 *
	 * @param menuUpperId the value for sys_menu.menu_upper_id
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setMenuUpperId(BigDecimal menuUpperId) {
		this.menuUpperId = menuUpperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.menu_name
	 *
	 * @return the value of sys_menu.menu_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.menu_name
	 *
	 * @param menuName the value for sys_menu.menu_name
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.menu_func_url
	 *
	 * @return the value of sys_menu.menu_func_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getMenuFuncUrl() {
		return menuFuncUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.menu_func_url
	 *
	 * @param menuFuncUrl the value for sys_menu.menu_func_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setMenuFuncUrl(String menuFuncUrl) {
		this.menuFuncUrl = menuFuncUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.menu_icon_url
	 *
	 * @return the value of sys_menu.menu_icon_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getMenuIconUrl() {
		return menuIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.menu_icon_url
	 *
	 * @param menuIconUrl the value for sys_menu.menu_icon_url
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setMenuIconUrl(String menuIconUrl) {
		this.menuIconUrl = menuIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.index_sort
	 *
	 * @return the value of sys_menu.index_sort
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public BigDecimal getIndexSort() {
		return indexSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.index_sort
	 *
	 * @param indexSort the value for sys_menu.index_sort
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setIndexSort(BigDecimal indexSort) {
		this.indexSort = indexSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.enable_mark
	 *
	 * @return the value of sys_menu.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getEnableMark() {
		return enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.enable_mark
	 *
	 * @param enableMark the value for sys_menu.enable_mark
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEnableMark(String enableMark) {
		this.enableMark = enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.crt_userid
	 *
	 * @return the value of sys_menu.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getCrtUserid() {
		return crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.crt_userid
	 *
	 * @param crtUserid the value for sys_menu.crt_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setCrtUserid(String crtUserid) {
		this.crtUserid = crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.crt_date
	 *
	 * @return the value of sys_menu.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public Date getCrtDate() {
		return crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.crt_date
	 *
	 * @param crtDate the value for sys_menu.crt_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.entry_userid
	 *
	 * @return the value of sys_menu.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public String getEntryUserid() {
		return entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.entry_userid
	 *
	 * @param entryUserid the value for sys_menu.entry_userid
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEntryUserid(String entryUserid) {
		this.entryUserid = entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.entry_date
	 *
	 * @return the value of sys_menu.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.entry_date
	 *
	 * @param entryDate the value for sys_menu.entry_date
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}
}