package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysMenuRole {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu_role.user_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	private String userRole;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu_role.menu_id
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	private BigDecimal menuId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu_role.enable_mark
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	private String enableMark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu_role.crt_userid
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	private String crtUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu_role.crt_date
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	private Date crtDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu_role.entry_userid
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	private String entryUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu_role.entry_date
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	private Date entryDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu_role.user_role
	 *
	 * @return the value of sys_menu_role.user_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public String getUserRole() {
		return userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu_role.user_role
	 *
	 * @param userRole the value for sys_menu_role.user_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu_role.menu_id
	 *
	 * @return the value of sys_menu_role.menu_id
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public BigDecimal getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu_role.menu_id
	 *
	 * @param menuId the value for sys_menu_role.menu_id
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public void setMenuId(BigDecimal menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu_role.enable_mark
	 *
	 * @return the value of sys_menu_role.enable_mark
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public String getEnableMark() {
		return enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu_role.enable_mark
	 *
	 * @param enableMark the value for sys_menu_role.enable_mark
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public void setEnableMark(String enableMark) {
		this.enableMark = enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu_role.crt_userid
	 *
	 * @return the value of sys_menu_role.crt_userid
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public String getCrtUserid() {
		return crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu_role.crt_userid
	 *
	 * @param crtUserid the value for sys_menu_role.crt_userid
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public void setCrtUserid(String crtUserid) {
		this.crtUserid = crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu_role.crt_date
	 *
	 * @return the value of sys_menu_role.crt_date
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public Date getCrtDate() {
		return crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu_role.crt_date
	 *
	 * @param crtDate the value for sys_menu_role.crt_date
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu_role.entry_userid
	 *
	 * @return the value of sys_menu_role.entry_userid
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public String getEntryUserid() {
		return entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu_role.entry_userid
	 *
	 * @param entryUserid the value for sys_menu_role.entry_userid
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public void setEntryUserid(String entryUserid) {
		this.entryUserid = entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu_role.entry_date
	 *
	 * @return the value of sys_menu_role.entry_date
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu_role.entry_date
	 *
	 * @param entryDate the value for sys_menu_role.entry_date
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}
}