package com.asi.huanan.service.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysRoleMapExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public SysRoleMapExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFkUserIdIsNull() {
            addCriterion("fk_user_id is null");
            return (Criteria) this;
        }

        public Criteria andFkUserIdIsNotNull() {
            addCriterion("fk_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andFkUserIdEqualTo(String value) {
            addCriterion("fk_user_id =", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdNotEqualTo(String value) {
            addCriterion("fk_user_id <>", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdGreaterThan(String value) {
            addCriterion("fk_user_id >", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("fk_user_id >=", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdLessThan(String value) {
            addCriterion("fk_user_id <", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdLessThanOrEqualTo(String value) {
            addCriterion("fk_user_id <=", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdLike(String value) {
            addCriterion("fk_user_id like", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdNotLike(String value) {
            addCriterion("fk_user_id not like", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdIn(List<String> values) {
            addCriterion("fk_user_id in", values, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdNotIn(List<String> values) {
            addCriterion("fk_user_id not in", values, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdBetween(String value1, String value2) {
            addCriterion("fk_user_id between", value1, value2, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdNotBetween(String value1, String value2) {
            addCriterion("fk_user_id not between", value1, value2, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleIsNull() {
            addCriterion("fk_user_role is null");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleIsNotNull() {
            addCriterion("fk_user_role is not null");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleEqualTo(String value) {
            addCriterion("fk_user_role =", value, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleNotEqualTo(String value) {
            addCriterion("fk_user_role <>", value, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleGreaterThan(String value) {
            addCriterion("fk_user_role >", value, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleGreaterThanOrEqualTo(String value) {
            addCriterion("fk_user_role >=", value, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleLessThan(String value) {
            addCriterion("fk_user_role <", value, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleLessThanOrEqualTo(String value) {
            addCriterion("fk_user_role <=", value, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleLike(String value) {
            addCriterion("fk_user_role like", value, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleNotLike(String value) {
            addCriterion("fk_user_role not like", value, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleIn(List<String> values) {
            addCriterion("fk_user_role in", values, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleNotIn(List<String> values) {
            addCriterion("fk_user_role not in", values, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleBetween(String value1, String value2) {
            addCriterion("fk_user_role between", value1, value2, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andFkUserRoleNotBetween(String value1, String value2) {
            addCriterion("fk_user_role not between", value1, value2, "fkUserRole");
            return (Criteria) this;
        }

        public Criteria andCrtUseridIsNull() {
            addCriterion("crt_userid is null");
            return (Criteria) this;
        }

        public Criteria andCrtUseridIsNotNull() {
            addCriterion("crt_userid is not null");
            return (Criteria) this;
        }

        public Criteria andCrtUseridEqualTo(String value) {
            addCriterion("crt_userid =", value, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridNotEqualTo(String value) {
            addCriterion("crt_userid <>", value, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridGreaterThan(String value) {
            addCriterion("crt_userid >", value, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridGreaterThanOrEqualTo(String value) {
            addCriterion("crt_userid >=", value, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridLessThan(String value) {
            addCriterion("crt_userid <", value, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridLessThanOrEqualTo(String value) {
            addCriterion("crt_userid <=", value, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridLike(String value) {
            addCriterion("crt_userid like", value, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridNotLike(String value) {
            addCriterion("crt_userid not like", value, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridIn(List<String> values) {
            addCriterion("crt_userid in", values, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridNotIn(List<String> values) {
            addCriterion("crt_userid not in", values, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridBetween(String value1, String value2) {
            addCriterion("crt_userid between", value1, value2, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtUseridNotBetween(String value1, String value2) {
            addCriterion("crt_userid not between", value1, value2, "crtUserid");
            return (Criteria) this;
        }

        public Criteria andCrtDateIsNull() {
            addCriterion("crt_date is null");
            return (Criteria) this;
        }

        public Criteria andCrtDateIsNotNull() {
            addCriterion("crt_date is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDateEqualTo(Date value) {
            addCriterion("crt_date =", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateNotEqualTo(Date value) {
            addCriterion("crt_date <>", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateGreaterThan(Date value) {
            addCriterion("crt_date >", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateGreaterThanOrEqualTo(Date value) {
            addCriterion("crt_date >=", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateLessThan(Date value) {
            addCriterion("crt_date <", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateLessThanOrEqualTo(Date value) {
            addCriterion("crt_date <=", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateIn(List<Date> values) {
            addCriterion("crt_date in", values, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateNotIn(List<Date> values) {
            addCriterion("crt_date not in", values, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateBetween(Date value1, Date value2) {
            addCriterion("crt_date between", value1, value2, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateNotBetween(Date value1, Date value2) {
            addCriterion("crt_date not between", value1, value2, "crtDate");
            return (Criteria) this;
        }

        public Criteria andEntryUseridIsNull() {
            addCriterion("entry_userid is null");
            return (Criteria) this;
        }

        public Criteria andEntryUseridIsNotNull() {
            addCriterion("entry_userid is not null");
            return (Criteria) this;
        }

        public Criteria andEntryUseridEqualTo(String value) {
            addCriterion("entry_userid =", value, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridNotEqualTo(String value) {
            addCriterion("entry_userid <>", value, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridGreaterThan(String value) {
            addCriterion("entry_userid >", value, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridGreaterThanOrEqualTo(String value) {
            addCriterion("entry_userid >=", value, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridLessThan(String value) {
            addCriterion("entry_userid <", value, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridLessThanOrEqualTo(String value) {
            addCriterion("entry_userid <=", value, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridLike(String value) {
            addCriterion("entry_userid like", value, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridNotLike(String value) {
            addCriterion("entry_userid not like", value, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridIn(List<String> values) {
            addCriterion("entry_userid in", values, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridNotIn(List<String> values) {
            addCriterion("entry_userid not in", values, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridBetween(String value1, String value2) {
            addCriterion("entry_userid between", value1, value2, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryUseridNotBetween(String value1, String value2) {
            addCriterion("entry_userid not between", value1, value2, "entryUserid");
            return (Criteria) this;
        }

        public Criteria andEntryDateIsNull() {
            addCriterion("entry_date is null");
            return (Criteria) this;
        }

        public Criteria andEntryDateIsNotNull() {
            addCriterion("entry_date is not null");
            return (Criteria) this;
        }

        public Criteria andEntryDateEqualTo(Date value) {
            addCriterion("entry_date =", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateNotEqualTo(Date value) {
            addCriterion("entry_date <>", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateGreaterThan(Date value) {
            addCriterion("entry_date >", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateGreaterThanOrEqualTo(Date value) {
            addCriterion("entry_date >=", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateLessThan(Date value) {
            addCriterion("entry_date <", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateLessThanOrEqualTo(Date value) {
            addCriterion("entry_date <=", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateIn(List<Date> values) {
            addCriterion("entry_date in", values, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateNotIn(List<Date> values) {
            addCriterion("entry_date not in", values, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateBetween(Date value1, Date value2) {
            addCriterion("entry_date between", value1, value2, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateNotBetween(Date value1, Date value2) {
            addCriterion("entry_date not between", value1, value2, "entryDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role_map
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 01 14:48:27 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}