package com.asi.huanan.service.dao.mybatis.model;

import java.util.Date;

public class SysRoleMap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_map.fk_user_id
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    private String fkUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_map.fk_user_role
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    private String fkUserRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_map.crt_userid
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    private String crtUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_map.crt_date
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    private Date crtDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_map.entry_userid
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    private String entryUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_map.entry_date
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_map.fk_user_id
     *
     * @return the value of sys_role_map.fk_user_id
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public String getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_map.fk_user_id
     *
     * @param fkUserId the value for sys_role_map.fk_user_id
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void setFkUserId(String fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_map.fk_user_role
     *
     * @return the value of sys_role_map.fk_user_role
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public String getFkUserRole() {
        return fkUserRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_map.fk_user_role
     *
     * @param fkUserRole the value for sys_role_map.fk_user_role
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void setFkUserRole(String fkUserRole) {
        this.fkUserRole = fkUserRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_map.crt_userid
     *
     * @return the value of sys_role_map.crt_userid
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public String getCrtUserid() {
        return crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_map.crt_userid
     *
     * @param crtUserid the value for sys_role_map.crt_userid
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void setCrtUserid(String crtUserid) {
        this.crtUserid = crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_map.crt_date
     *
     * @return the value of sys_role_map.crt_date
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public Date getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_map.crt_date
     *
     * @param crtDate the value for sys_role_map.crt_date
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void setCrtDate(Date crtDate) {
        this.crtDate = crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_map.entry_userid
     *
     * @return the value of sys_role_map.entry_userid
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public String getEntryUserid() {
        return entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_map.entry_userid
     *
     * @param entryUserid the value for sys_role_map.entry_userid
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void setEntryUserid(String entryUserid) {
        this.entryUserid = entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_map.entry_date
     *
     * @return the value of sys_role_map.entry_date
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_map.entry_date
     *
     * @param entryDate the value for sys_role_map.entry_date
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}