package com.asi.huanan.service.dao.mybatis.model;

import java.util.Date;

public class SysRole {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role.user_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	private String userRole;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role.role_name
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	private String roleName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role.enable_mark
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	private String enableMark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role.crt_userid
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	private String crtUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role.crt_date
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	private Date crtDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role.entry_userid
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	private String entryUserid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role.entry_date
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	private Date entryDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role.def_role_flg
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	private String defRoleFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.user_role
	 *
	 * @return the value of sys_role.user_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public String getUserRole() {
		return userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.user_role
	 *
	 * @param userRole the value for sys_role.user_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.role_name
	 *
	 * @return the value of sys_role.role_name
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.role_name
	 *
	 * @param roleName the value for sys_role.role_name
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.enable_mark
	 *
	 * @return the value of sys_role.enable_mark
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public String getEnableMark() {
		return enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.enable_mark
	 *
	 * @param enableMark the value for sys_role.enable_mark
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public void setEnableMark(String enableMark) {
		this.enableMark = enableMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.crt_userid
	 *
	 * @return the value of sys_role.crt_userid
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public String getCrtUserid() {
		return crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.crt_userid
	 *
	 * @param crtUserid the value for sys_role.crt_userid
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public void setCrtUserid(String crtUserid) {
		this.crtUserid = crtUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.crt_date
	 *
	 * @return the value of sys_role.crt_date
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public Date getCrtDate() {
		return crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.crt_date
	 *
	 * @param crtDate the value for sys_role.crt_date
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.entry_userid
	 *
	 * @return the value of sys_role.entry_userid
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public String getEntryUserid() {
		return entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.entry_userid
	 *
	 * @param entryUserid the value for sys_role.entry_userid
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public void setEntryUserid(String entryUserid) {
		this.entryUserid = entryUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.entry_date
	 *
	 * @return the value of sys_role.entry_date
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.entry_date
	 *
	 * @param entryDate the value for sys_role.entry_date
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.def_role_flg
	 *
	 * @return the value of sys_role.def_role_flg
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public String getDefRoleFlg() {
		return defRoleFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.def_role_flg
	 *
	 * @param defRoleFlg the value for sys_role.def_role_flg
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	public void setDefRoleFlg(String defRoleFlg) {
		this.defRoleFlg = defRoleFlg;
	}
}