package com.asi.huanan.service.dao.mybatis.model;

import java.util.Date;

public class SysUserPersonal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.user_id
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.page_bg
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    private String pageBg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.crt_userid
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    private String crtUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.crt_date
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    private Date crtDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.entry_userid
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    private String entryUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.entry_date
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.user_id
     *
     * @return the value of sys_user_personal.user_id
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.user_id
     *
     * @param userId the value for sys_user_personal.user_id
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.page_bg
     *
     * @return the value of sys_user_personal.page_bg
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public String getPageBg() {
        return pageBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.page_bg
     *
     * @param pageBg the value for sys_user_personal.page_bg
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public void setPageBg(String pageBg) {
        this.pageBg = pageBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.crt_userid
     *
     * @return the value of sys_user_personal.crt_userid
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public String getCrtUserid() {
        return crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.crt_userid
     *
     * @param crtUserid the value for sys_user_personal.crt_userid
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public void setCrtUserid(String crtUserid) {
        this.crtUserid = crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.crt_date
     *
     * @return the value of sys_user_personal.crt_date
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public Date getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.crt_date
     *
     * @param crtDate the value for sys_user_personal.crt_date
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public void setCrtDate(Date crtDate) {
        this.crtDate = crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.entry_userid
     *
     * @return the value of sys_user_personal.entry_userid
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public String getEntryUserid() {
        return entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.entry_userid
     *
     * @param entryUserid the value for sys_user_personal.entry_userid
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public void setEntryUserid(String entryUserid) {
        this.entryUserid = entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.entry_date
     *
     * @return the value of sys_user_personal.entry_date
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.entry_date
     *
     * @param entryDate the value for sys_user_personal.entry_date
     *
     * @mbg.generated Wed May 27 10:18:56 CST 2020
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}