package com.asi.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.asi.service.dao.mybatis.model.AppHoliday;
import com.asi.service.dao.mybatis.model.AppHolidayExample;

@Mapper
public interface AppHolidayMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	long countByExample(AppHolidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	int deleteByExample(AppHolidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	int deleteByPrimaryKey(String uuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	int insert(AppHoliday record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	int insertSelective(AppHoliday record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	List<AppHoliday> selectByExample(AppHolidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	AppHoliday selectByPrimaryKey(String uuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	int updateByExampleSelective(@Param("record") AppHoliday record, @Param("example") AppHolidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	int updateByExample(@Param("record") AppHoliday record, @Param("example") AppHolidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	int updateByPrimaryKeySelective(AppHoliday record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table APP_HOLIDAY
	 * 
	 * @mbg.generated Wed Apr 10 17:56:57 CST 2019
	 */
	int updateByPrimaryKey(AppHoliday record);
}