package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.SysAccount;
import com.asi.huanan.service.dao.mybatis.model.SysAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAccountMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	long countByExample(SysAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int deleteByExample(SysAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int insert(SysAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int insertSelective(SysAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	List<SysAccount> selectByExample(SysAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	SysAccount selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int updateByExampleSelective(@Param("record") SysAccount record, @Param("example") SysAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int updateByExample(@Param("record") SysAccount record, @Param("example") SysAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int updateByPrimaryKeySelective(SysAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_account
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int updateByPrimaryKey(SysAccount record);
}