package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.SysFunctionUiField;
import com.asi.huanan.service.dao.mybatis.model.SysFunctionUiFieldExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFunctionUiFieldMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	long countByExample(SysFunctionUiFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int deleteByExample(SysFunctionUiFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int deleteByPrimaryKey(BigDecimal functionUiFieldId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int insert(SysFunctionUiField record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int insertSelective(SysFunctionUiField record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	List<SysFunctionUiField> selectByExample(SysFunctionUiFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	SysFunctionUiField selectByPrimaryKey(BigDecimal functionUiFieldId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int updateByExampleSelective(@Param("record") SysFunctionUiField record,
			@Param("example") SysFunctionUiFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int updateByExample(@Param("record") SysFunctionUiField record,
			@Param("example") SysFunctionUiFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int updateByPrimaryKeySelective(SysFunctionUiField record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_field
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int updateByPrimaryKey(SysFunctionUiField record);
	
	List<SysFunctionUiField> selectByFieldIdList(@Param("list") List<BigDecimal> idList);
}