package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.SysFunctionUiButton;
import com.asi.huanan.service.dao.mybatis.model.SysFunctionUiButtonExample;
import com.asi.huanan.service.dao.mybatis.model.SysIndex;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFunctionUiButtonMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	long countByExample(SysFunctionUiButtonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int deleteByExample(SysFunctionUiButtonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int deleteByPrimaryKey(BigDecimal functionUiButtonId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int insert(SysFunctionUiButton record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int insertSelective(SysFunctionUiButton record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	List<SysFunctionUiButton> selectByExample(SysFunctionUiButtonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	SysFunctionUiButton selectByPrimaryKey(BigDecimal functionUiButtonId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int updateByExampleSelective(@Param("record") SysFunctionUiButton record,
			@Param("example") SysFunctionUiButtonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int updateByExample(@Param("record") SysFunctionUiButton record,
			@Param("example") SysFunctionUiButtonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int updateByPrimaryKeySelective(SysFunctionUiButton record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_function_ui_button
	 *
	 * @mbg.generated Fri Apr 17 16:57:55 CST 2020
	 */
	int updateByPrimaryKey(SysFunctionUiButton record);

	List<SysFunctionUiButton> selectByButtonIdList(@Param("list") List<BigDecimal> idList);
}