package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.SysIndex;
import com.asi.huanan.service.dao.mybatis.model.SysIndexExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysIndexMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	long countByExample(SysIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int deleteByExample(SysIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int deleteByPrimaryKey(BigDecimal indexId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int insert(SysIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int insertSelective(SysIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	List<SysIndex> selectByExample(SysIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	SysIndex selectByPrimaryKey(BigDecimal indexId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int updateByExampleSelective(@Param("record") SysIndex record, @Param("example") SysIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int updateByExample(@Param("record") SysIndex record, @Param("example") SysIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int updateByPrimaryKeySelective(SysIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_index
	 *
	 * @mbg.generated Tue Mar 31 14:00:52 CST 2020
	 */
	int updateByPrimaryKey(SysIndex record);

	List<SysIndex> selectByIdexidList(@Param("list") List<BigDecimal> indexIdList);
}