package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.SysMenuRole;
import com.asi.huanan.service.dao.mybatis.model.SysMenuRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuRoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_menu_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	long countByExample(SysMenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_menu_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	int deleteByExample(SysMenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_menu_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	int insert(SysMenuRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_menu_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	int insertSelective(SysMenuRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_menu_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	List<SysMenuRole> selectByExample(SysMenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_menu_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	int updateByExampleSelective(@Param("record") SysMenuRole record, @Param("example") SysMenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_menu_role
	 *
	 * @mbg.generated Wed Apr 01 11:12:21 CST 2020
	 */
	int updateByExample(@Param("record") SysMenuRole record, @Param("example") SysMenuRoleExample example);
}