package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.SysRole;
import com.asi.huanan.service.dao.mybatis.model.SysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	long countByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	int deleteByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	int deleteByPrimaryKey(String userRole);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	int insert(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	int insertSelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	List<SysRole> selectByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	SysRole selectByPrimaryKey(String userRole);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	int updateByExampleSelective(@Param("record") SysRole record, @Param("example") SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	int updateByExample(@Param("record") SysRole record, @Param("example") SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	int updateByPrimaryKeySelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Fri Apr 17 09:55:24 CST 2020
	 */
	int updateByPrimaryKey(SysRole record);
}