package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.SysRoleMap;
import com.asi.huanan.service.dao.mybatis.model.SysRoleMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    long countByExample(SysRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    int deleteByExample(SysRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    int insert(SysRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    int insertSelective(SysRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    List<SysRoleMap> selectByExample(SysRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRoleMap record, @Param("example") SysRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_map
     *
     * @mbg.generated Mon Jun 01 14:48:27 CST 2020
     */
    int updateByExample(@Param("record") SysRoleMap record, @Param("example") SysRoleMapExample example);
}